# Generated by Django 4.2.1 on 2023-05-30 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                ("idIngredient", models.AutoField(primary_key=True, serialize=False)),
                (
                    "nomIngredient",
                    models.CharField(
                        max_length=50, verbose_name="le nom de cet ingredient"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pizza",
            fields=[
                ("idPizza", models.AutoField(primary_key=True, serialize=False)),
                (
                    "nomPizza",
                    models.CharField(
                        max_length=50, verbose_name="le nom de cette Pizza"
                    ),
                ),
                (
                    "prix",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="le prix "
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Composition",
            fields=[
                ("idComposition", models.AutoField(primary_key=True, serialize=False)),
                (
                    "quantite",
                    models.CharField(max_length=100, verbose_name="la quantité"),
                ),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applipizza.ingredient",
                    ),
                ),
                (
                    "pizza",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applipizza.pizza",
                    ),
                ),
            ],
            options={
                "unique_together": {("ingredient", "pizza")},
            },
        ),
    ]
