# Generated by Django 4.2.1 on 2023-05-31 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applipizza", "0003_remove_pizza_prix"),
    ]

    operations = [
        migrations.AddField(
            model_name="pizza",
            name="prix",
            field=models.DecimalField(
                decimal_places=2, max_digits=4, null=True, verbose_name="le prix "
            ),
        ),
    ]
